#!/usr/bin/env python3
"""Measure the two v3 lifetime overlays for every official parameter set.

The source trees are generated by upstream's ``gen_pqm4_sources.sh``.  This
script compiles only the two affected translation units with the RP2350 Arm
flags, reads GCC's static stack-usage records, and records object-code sizes.
Functional validation is a separate gate in ``test_sqisign_v3_all_params.sh``.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PARAMETERS = ("p324_3", "p500_27", "p664_17")
UNITS = {
    "lll_dim4.c": "quat_lll_dual_reduce_ideal",
    "sign.c": "protocols_sign",
}
DEFAULT_OFFICIAL_COMMIT = "6d017708db403bf83977fa70770fc4f7f9e9ff21"
DEFAULT_ADAPTED_COMMIT = "874658c64aa2e20f53b1f4d696144723d558ed5c"


def run(*args: str | Path, cwd: Path | None = None) -> str:
    return subprocess.run(
        [str(arg) for arg in args],
        cwd=cwd,
        check=True,
        text=True,
        capture_output=True,
    ).stdout.strip()


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def check_tree(path: Path, commit: str) -> None:
    if run("git", "-C", path, "rev-parse", "HEAD") != commit:
        raise ValueError(f"unexpected commit for {path}")
    if run("git", "-C", path, "status", "--porcelain", "--untracked-files=no"):
        raise ValueError(f"tracked files are dirty in {path}")


def stack_record(path: Path, function: str) -> dict[str, object]:
    matches: list[dict[str, object]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        fields = line.rsplit("\t", 2)
        if len(fields) != 3:
            raise ValueError(f"malformed stack-usage record: {line!r}")
        observed = fields[0].rsplit(":", 1)[-1]
        if observed == function:
            matches.append(
                {
                    "frame_bytes": int(fields[1]),
                    "qualifiers": fields[2].split(","),
                    "record": line,
                }
            )
    if len(matches) != 1:
        raise ValueError(f"expected one {function} record in {path}, got {matches}")
    if "static" not in matches[0]["qualifiers"] or "dynamic" in matches[0]["qualifiers"]:
        raise ValueError(f"non-static frame for {function}: {matches[0]}")
    return matches[0]


def object_sections(size_tool: Path, object_path: Path) -> dict[str, int]:
    lines = run(size_tool, object_path).splitlines()
    if len(lines) != 2:
        raise ValueError(f"unexpected size output for {object_path}: {lines}")
    values = lines[1].split()
    if len(values) < 6:
        raise ValueError(f"unexpected size row for {object_path}: {values}")
    return {"text": int(values[0]), "data": int(values[1]), "bss": int(values[2])}


def compile_unit(
    compiler: Path,
    size_tool: Path,
    source_tree: Path,
    variant: str,
    parameter: str,
    unit: str,
    function: str,
    build_root: Path,
) -> dict[str, object]:
    generated = source_tree / "src/pqm4" / f"sqisign_{parameter}" / "m4f"
    source = generated / unit
    if not source.is_file():
        raise ValueError(f"missing generated source: {source}")
    output_dir = build_root / variant / parameter
    output_dir.mkdir(parents=True, exist_ok=True)
    object_path = output_dir / f"{unit}.o"
    command = [
        compiler,
        "-DDISABLE_NAMESPACING",
        "-DENABLE_SIGN",
        "-DNDEBUG",
        "-DRADIX_32",
        "-DRANDOMBYTES_C",
        "-DSQISIGN_BUILD_TYPE_REF",
        "-DSQISIGN_GF_IMPL_SAT32",
        "-DSQISIGN_SINGLE_THREADED",
        f"-DSQISIGN_VARIANT={parameter}",
        "-DTARGET_ARM",
        f"-I{ROOT / 'src/platform/rp2350_v3'}",
        f"-I{generated}",
        f"-I{source_tree / 'src/common/generic/include'}",
        f"-I{source_tree / 'src/common/ref/include'}",
        "-mcpu=cortex-m33",
        "-mthumb",
        "-march=armv8-m.main+fp+dsp",
        "-mcmse",
        "-mfloat-abi=softfp",
        "-O3",
        "-std=gnu11",
        "-fno-strict-aliasing",
        "-fstack-usage",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wvla",
        "-Walloca",
        "-Wall",
        "-Wextra",
        "-Werror",
        "-Wno-error=attributes",
        "-Wno-error=missing-braces",
        "-Wno-error=unused-variable",
        "-Wno-error=vla",
        "-Wno-unused-function",
        "-Wno-unused-parameter",
        "-Wno-maybe-uninitialized",
        "-c",
        source,
        "-o",
        object_path,
    ]
    subprocess.run([str(item) for item in command], check=True)
    usage_path = object_path.with_suffix(".su")
    usage = stack_record(usage_path, function)
    return {
        "variant": variant,
        "parameter": parameter,
        "translation_unit": unit,
        "function": function,
        "frame_bytes": usage["frame_bytes"],
        "stack_qualifiers": usage["qualifiers"],
        "source_sha256": sha256(source),
        "object_sha256": sha256(object_path),
        "object_file_bytes": object_path.stat().st_size,
        "object_sections": object_sections(size_tool, object_path),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--official-source", type=Path, default=ROOT / "work/official-v3"
    )
    parser.add_argument(
        "--adapted-source", type=Path, default=ROOT / "work/v3-lowmem-d3"
    )
    parser.add_argument("--official-commit", default=DEFAULT_OFFICIAL_COMMIT)
    parser.add_argument("--adapted-commit", default=DEFAULT_ADAPTED_COMMIT)
    parser.add_argument("--compiler", type=Path, required=True)
    parser.add_argument("--size-tool", type=Path, required=True)
    parser.add_argument(
        "--build-root", type=Path, default=ROOT / "build-v3-all-params-analysis"
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "results/v3/analysis/lifetime-all-params-2026-09-04.json",
    )
    parser.add_argument(
        "--csv-output",
        type=Path,
        default=ROOT / "results/v3/analysis/lifetime-all-params-2026-09-04.csv",
    )
    parser.add_argument(
        "--host-validation",
        type=Path,
        default=ROOT / "results/v3/host/validation-all-params-2026-09-04.json",
    )
    args = parser.parse_args()

    check_tree(args.official_source, args.official_commit)
    check_tree(args.adapted_source, args.adapted_commit)
    compiler_version = run(args.compiler, "--version").splitlines()[0]

    rows: list[dict[str, object]] = []
    for parameter in PARAMETERS:
        for variant, source in (
            ("official", args.official_source),
            ("two_function_lifetime", args.adapted_source),
        ):
            for unit, function in UNITS.items():
                rows.append(
                    compile_unit(
                        args.compiler,
                        args.size_tool,
                        source,
                        variant,
                        parameter,
                        unit,
                        function,
                        args.build_root,
                    )
                )

    comparisons: list[dict[str, object]] = []
    for parameter in PARAMETERS:
        for unit, function in UNITS.items():
            selected = {
                str(row["variant"]): row
                for row in rows
                if row["parameter"] == parameter and row["translation_unit"] == unit
            }
            official = int(selected["official"]["frame_bytes"])
            adapted = int(selected["two_function_lifetime"]["frame_bytes"])
            comparisons.append(
                {
                    "parameter": parameter,
                    "translation_unit": unit,
                    "function": function,
                    "official_frame_bytes": official,
                    "adapted_frame_bytes": adapted,
                    "reduction_bytes": official - adapted,
                    "reduction_percent": round(100.0 * (official - adapted) / official, 4),
                }
            )

    if not all(row["reduction_bytes"] > 0 for row in comparisons):
        raise ValueError(f"an affected frame did not decrease: {comparisons}")
    host_validation = json.loads(args.host_validation.read_text(encoding="utf-8"))
    if (
        host_validation.get("status") != "PASS"
        or host_validation["decision"]["known_answer_vectors_passed"] != 600
        or host_validation["provenance"]["official"]["commit"]
        != args.official_commit
        or host_validation["provenance"]["two_function_lifetime"]["commit"]
        != args.adapted_commit
    ):
        raise ValueError("all-parameter host validation is absent or stale")

    result = {
        "schema": "sqisign-v3-two-function-all-parameter-frame-audit-v1",
        "status": "PASS",
        "scope": {
            "parameters": list(PARAMETERS),
            "functions": list(UNITS.values()),
            "target": "Arm Cortex-M33 softfp object compilation",
            "functional_gate": "results/v3/host/validation-all-params-2026-09-04.json",
            "not_in_scope": [
                "RP2350 whole-image watermarks for p500_27 or p664_17",
                "whole-program interrupt/MSP bound",
            ],
        },
        "provenance": {
            "official_commit": args.official_commit,
            "adapted_commit": args.adapted_commit,
            "compiler": compiler_version,
        },
        "rows": rows,
        "comparisons": comparisons,
        "decision": {
            "all_three_official_parameter_sets_compiled": True,
            "two_distinct_functions_measured": True,
            "all_six_affected_frames_reduced": True,
            "all_600_official_known_answer_vectors_passed": True,
            "functional_equivalence_established_for_tested_vectors": True,
            "functional_equivalence_established_for_all_inputs": False,
        },
        "functional_gate_sha256": sha256(args.host_validation),
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    args.csv_output.parent.mkdir(parents=True, exist_ok=True)
    with args.csv_output.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(comparisons[0]), lineterminator="\n")
        writer.writeheader()
        writer.writerows(comparisons)
    print("v3 two-function/all-parameter Arm frame audit: PASS")
    for row in comparisons:
        print(
            f"{row['parameter']} {row['function']}: "
            f"{row['official_frame_bytes']} -> {row['adapted_frame_bytes']} "
            f"(-{row['reduction_bytes']} bytes)"
        )
    print(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
